# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Install pnpm globally
RUN npm install -g pnpm

# Set working directory
WORKDIR /app

# Copy package files and lockfile
COPY package.json pnpm-lock.yaml ./

# Install dependencies without running prepare scripts
RUN pnpm install --ignore-scripts

# Copy rest of the source code
COPY . .

# Build the project
RUN pnpm run build

# Expose any relevant ports if needed (optional)

# Start the MCP server
CMD ["node", "build/index.js"]
